"""Generate `_generated.py` (models, OPERATIONS, TrigifyPort, TrigifyClient) from the Trigify
spec merged with the hand-authored legacy spec.

Usage: python -m trekk_harvester.trigify.codegen <spec> <legacy spec> <out>
(recipe: `just trigify-client`)
"""

import json
import sys
from pathlib import Path

from trekk_harvester.trigify.operation import Pagination
from trekk_harvester.trigify.spec import (
    AUTH_HEADER,
    Schema,
    Spec,
    classify_pagination,
    iter_operations,
    load_specs,
    pinned_sha256,
    py_identifier,
    resolve_all_of,
    success_status,
    types_of,
)

HEADER = '''\
# Generated by trekk_harvester.trigify.codegen from spec/trigify/openapi.json and
# spec/trigify/legacy.json: do not edit.
# Regenerate with `just trigify-client`; a unit test fails when this file drifts from the spec.
"""Typed Trigify client generated from the recovered OpenAPI spec."""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Any, Final, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field

from trekk_harvester.trigify.client import BaseClient
from trekk_harvester.trigify.operation import Operation as _Operation
from trekk_harvester.trigify.operation import Pagination as _Pagination
from trekk_harvester.trigify.operation import QueryParam as _QueryParam
'''
MODEL_CONFIG = '    model_config = ConfigDict(extra="allow", populate_by_name=True)'
RESERVED = frozenset(
    {
        "Any",
        "Final",
        "Literal",
        "Protocol",
        "Mapping",
        "MappingProxyType",
        "BaseModel",
        "ConfigDict",
        "Field",
        "BaseClient",
        "TrigifyClient",
        "TrigifyPort",
    }
)
SCALARS = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "null": "None"}


def pascal(name: str) -> str:
    parts = [p for p in "".join(c if c.isalnum() else " " for c in name).split() if p]
    return "".join(p[0].upper() + p[1:] for p in parts)


def literal(value: object) -> str:
    return json.dumps(value) if isinstance(value, str) else repr(value)


def union(members: list[str]) -> str:
    unique = list(dict.fromkeys(members))
    if "None" in unique:
        unique = [m for m in unique if m != "None"] + ["None"]
    return " | ".join(unique)


def optional(annotation: str) -> str:
    """`annotation | None` unless the top-level union already admits None."""
    return (
        annotation
        if annotation == "None" or annotation.endswith(" | None")
        else annotation + " | None"
    )


class Generator:
    def __init__(self, spec: Spec) -> None:
        self.spec = spec
        self.components: dict[str, Schema] = spec["components"]["schemas"]
        self.blocks: list[str] = []
        self.names: set[str] = set(RESERVED)
        self.fields: set[str] = set()

    def claim(self, name: str) -> str:
        if name in self.names or not name.isidentifier():
            raise ValueError(f"generated name {name!r} is taken or invalid")
        self.names.add(name)
        return name

    # ------------------------------------------------------------------ schemas

    def type_of(self, node: Schema, context: str) -> str:
        """The annotation for `node`; inline objects become classes named `context`."""
        if "$ref" in node:
            name = node["$ref"].removeprefix("#/components/schemas/")
            target = self.components[name]
            nullable = "null" in types_of(target) and "object" in types_of(target)
            return union([name, "None"]) if nullable else name
        if "allOf" in node:
            return self.type_of(resolve_all_of(self.spec, node), context)
        for combinator in ("anyOf", "oneOf"):
            if combinator in node:
                return union(
                    [
                        self.type_of(member, f"{context}Option{index}")
                        for index, member in enumerate(node[combinator])
                    ]
                )
        types = types_of(node)
        if "const" in node:
            return f"Literal[{literal(node['const'])}]"
        if "enum" in node:
            values = [v for v in node["enum"] if v is not None]
            nullable = "null" in types or None in node["enum"]
            members = [f"Literal[{', '.join(literal(v) for v in values)}]"]
            return union([*members, "None"] if nullable else members)
        if not types:
            return "Any"
        return union([self.single(t, node, context) for t in types])

    def single(self, kind: str, node: Schema, context: str) -> str:
        if kind in SCALARS:
            return SCALARS[kind]
        if kind == "array":
            return f"list[{self.type_of(node.get('items', {}), context + 'Item')}]"
        if kind != "object":
            raise ValueError(f"unsupported type {kind!r} at {context}")
        if node.get("properties"):
            return self.model(context, node)
        extra = node.get("additionalProperties", {})
        value = "Any" if extra in ({}, True) else self.type_of(extra, context + "Value")
        return f"dict[str, {value}]"

    def model(self, name: str, node: Schema) -> str:
        self.claim(name)
        required = set(node.get("required", []))
        lines = [f"class {name}(BaseModel):", MODEL_CONFIG, ""]
        for prop, schema in node["properties"].items():
            field = py_identifier(prop, field=True)
            self.fields.add(field)
            annotation = self.type_of(schema, name + pascal(prop))
            alias = f'alias="{prop}"' if field != prop else ""
            if prop in required:
                default = f" = Field({alias})" if alias else ""
            else:
                annotation = optional(annotation)
                default = f" = Field(default=None, {alias})" if alias else " = None"
            lines.append(f"    {field}: {annotation}{default}")
        self.blocks.append("\n".join(lines).rstrip())
        return name

    def component(self, name: str, node: Schema) -> None:
        if "object" in types_of(node):
            self.model(name, node)
        else:
            self.claim(name)
            self.blocks.append(f"type {name} = {self.type_of(node, name)}")

    def class_of(self, node: Schema, context: str) -> str:
        annotation = self.type_of(node, context)
        if annotation not in self.names or annotation in RESERVED:
            raise ValueError(f"{context} is not a model: {annotation}")
        return annotation

    # ------------------------------------------------------------------ operations

    def operations(self) -> tuple[list[str], list[str], list[str]]:
        table: list[str] = []
        port: list[str] = []
        client: list[str] = []
        for name, method, path, operation in iter_operations(self.spec):
            context = pascal(name)
            params = [p for p in operation.get("parameters", []) if p["name"] != AUTH_HEADER]
            path_params = [p["name"] for p in params if p["in"] == "path"]
            query = [p for p in params if p["in"] == "query"]
            if {p["in"] for p in params} - {"path", "query"}:
                raise ValueError(f"{name}: unsupported parameter location")
            response = self.class_of(
                operation["responses"][str(success_status(operation))]["content"][
                    "application/json"
                ]["schema"],
                context + "Response",
            )
            body = operation.get("requestBody")
            body_class = (
                self.class_of(body["content"]["application/json"]["schema"], context + "Request")
                if body
                else None
            )
            body_required = bool(body and body.get("required"))

            signature = ["self"]
            signature += [f"{py_identifier(p)}: str" for p in path_params]
            if path_params:
                signature.append("/")
            if body_class:
                signature.append(
                    f"body: {body_class}" if body_required else f"body: {body_class} | None = None"
                )
            query_fields = []
            if query:
                signature.append("*")
            for param in query:
                py = py_identifier(param["name"])
                annotation = self.type_of(param["schema"], context + pascal(param["name"]))
                if param.get("required"):
                    signature.append(f"{py}: {annotation}")
                else:
                    signature.append(f"{py}: {optional(annotation)} = None")
                query_fields.append((param["name"], py, bool(param.get("required"))))
            names = [s.split(":")[0] for s in signature]
            if len(names) != len(set(names)):
                raise ValueError(f"{name}: parameter names collide: {names}")
            head = f"    async def {name}({', '.join(signature)}) -> {response}:"
            port.append(f"{head} ...")

            args = [f'OPERATIONS["{name}"]', response]
            if path_params:
                args.append(f"path=({', '.join(py_identifier(p) for p in path_params)},)")
            if query_fields:
                pairs = ", ".join(f'"{q}": {py}' for q, py, _ in query_fields)
                args.append(f"query={{{pairs}}}")
            if body_class:
                args.append("body=body")
            client.append(f"{head}\n        return await self._call({', '.join(args)})")

            pagination = classify_pagination(self.spec, operation)
            query_params = "".join(
                f"_QueryParam({q!r}, {py!r}, {r!r}), " for q, py, r in query_fields
            )
            table.append(
                f'    "{name}": _Operation(\n'
                f'        name="{name}",\n'
                f'        method="{method.upper()}",\n'
                f'        path="{path}",\n'
                f"        path_params={tuple(path_params)!r},\n"
                f"        query_params=({query_params}),\n"
                f"        body={body_class},\n"
                f"        body_required={body_required!r},\n"
                f"        response={response},\n"
                f"        status={success_status(operation)},\n"
                f"        pagination={pagination_source(pagination)},\n"
                "    ),"
            )
        return table, port, client


def pagination_source(pagination: Pagination | None) -> str:
    if pagination is None:
        return "None"
    return (
        f"_Pagination({pagination.kind!r}, {pagination.param!r}, {pagination.size_param!r}, "
        f"{pagination.location!r}, {pagination.base!r}, {pagination.default_size!r})"
    )


def generate(spec: Spec, sha256: str, legacy_sha256: str) -> str:
    """The module for the merged `spec`, pinning both source files' hashes."""
    generator = Generator(spec)
    for name, node in generator.components.items():
        generator.component(name, node)
    table, port, client = generator.operations()
    shadowing = generator.fields & generator.names
    if shadowing:
        raise ValueError(f"field names shadow generated names: {sorted(shadowing)}")
    return "\n".join(
        [
            HEADER,
            f'SPEC_SHA256: Final = "{sha256}"',
            f'LEGACY_SPEC_SHA256: Final = "{legacy_sha256}"',
            "",
            *(f"\n{block}\n" for block in generator.blocks),
            "",
            "class TrigifyPort(Protocol):",
            '    """Every Trigify operation; `TrigifyClient` is the HTTP implementation."""',
            "",
            *port,
            "",
            "",
            "class TrigifyClient(BaseClient):",
            "",
            "\n\n".join(client),
            "",
            "",
            "OPERATIONS: Final[Mapping[str, _Operation]] = MappingProxyType({",
            *table,
            "})",
            "",
        ]
    )


def main(argv: list[str]) -> None:
    spec_path, legacy_path, out = (Path(a) for a in argv)
    pins = (pinned_sha256(spec_path), pinned_sha256(legacy_path))
    out.write_text(generate(load_specs(spec_path, legacy_path, pins=pins), *pins))


if __name__ == "__main__":
    main(sys.argv[1:])
